export const PRODUCTION_ENDPOINT = 'https://joann-allocation-dev.impactanalytics.co/'
export const DEVELOPMENT_ENDPOINT = 'https://joann-allocation-dev.impactanalytics.co/'
// export const DEVELOPMENT_ENDPOINT = 'http://ec2co-ecsel-r8l7dlzkuyqk-1223714672.us-east-1.elb.amazonaws.com/api'
export const TEST_ENDPOINT = 'https://joann-allocation-dev.impactanalytics.co/'
// export const DEVELOPMENT_ENDPOINT = 'https://e67f2v2ozg.execute-api.us-east-1.amazonaws.com/development/api'
